### ISSUE TITLE
点击图标同步出现问题

### ISSUE THREAD

**Issue by WyInnovate** [Yimien/plugin-memos-sync-helper#1]
问题：请检查插件配置是否正确！ v3.0.16
控制台输出：
```
Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at HTMLDivElement.<anonymous> (main.f3092200a4c336e05404.js:6635:170)
（匿名） @ main.f3092200a4c336e05404.js:6635
```

**Comment by Yimien** [comment]
你插件带星号的都配置完了吗，这个报错我还没找到原因，但是不影响同步

**Comment by Yimien** [comment]
尝试修复了一下，虽然不太懂，但好像没报错了

**Comment by 5kyfkr** [comment]
我也是报这个错，带星号的也配置完了

**Comment by mozhux** [comment]
我也是报错这个

**Comment by WyInnovate** [comment]
> 你插件带星号的都配置完了吗，这个报错我还没找到原因，但是不影响同步

# 问题补充
试了最新的一版，发现了问题所在，当你第一次使用该插件的时候，选同步方案为：同步为单独的文档，然后文档路径此时是不带✳️的，然后不输入文档路径去点同步就不会同步数据下来！
# 新问题
## Memos原文如下
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/40713819/bb2ffc96-936b-405b-b653-c586405d8373)
## 同步过来后如下
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/40713819/a8ae0ac9-ba4b-4a0b-a1da-5ad2f0ad3391)
我看了下同步到思源本地的代码块基本上都是这种问题

**Comment by 5kyfkr** [comment]
> > 你插件带星号的都配置完了吗，这个报错我还没找到原因，但是不影响同步
> 
> # 问题补充
> 试了最新的一版，发现了问题所在，当你第一次使用该插件的时候，选同步方案为：同步为单独的文档，然后文档路径此时是不带✳️的，然后不输入文档路径去点同步就不会同步数据下来！

我东西都填了也一样报错,0.1.1版本
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/63196026/713da653-1f2a-4d68-92a1-51a5533edd84)

**Comment by WyInnovate** [comment]
> > > 你插件带星号的都配置完了吗，这个报错我还没找到原因，但是不影响同步
> > 
> > 
> > # 问题补充
> > 试了最新的一版，发现了问题所在，当你第一次使用该插件的时候，选同步方案为：同步为单独的文档，然后文档路径此时是不带✳️的，然后不输入文档路径去点同步就不会同步数据下来！
> 
> 我东西都填了也一样报错,0.1.1版本，校验是能正常通过的 ![image](https://private-user-images.githubusercontent.com/63196026/336273261-713da653-1f2a-4d68-92a1-51a5533edd84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NzQwNTUsIm5iZiI6MTcxNzQ3Mzc1NSwicGF0aCI6Ii82MzE5NjAyNi8zMzYyNzMyNjEtNzEzZGE2NTMtMWYyYS00ZDY4LTkyYTEtNTFhNTUzM2VkZDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA0MDIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZmIyYjFkY2I2N2EyNmIxZGIyMDEzOTU0Nzg0ZjU0NzEwMDZkOTcwOTYwNzIxNzI4NzZlYzc3ODA2MWUyY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1F2eN0rbfiDCvG9IUvnLm_9Ozjgj1GMfSfHSQa2-6Os)

@5kyfkr 看看开发者工具里提示啥内容

**Comment by Yimien** [comment]
已修复
