### ISSUE TITLE
tag 无法准确识别

### ISSUE THREAD

**Issue by chenxuan520** [Yimien/plugin-memos-sync-helper#12]
类似下图,有些tag无法识别,有些可以识别,但是在memos中是完全可以识别的,不清楚会不会是tag后面需要空格导致的
![image](https://github.com/user-attachments/assets/e1d8dd1e-8246-410c-b1a2-41aea9bcabb9)

**Comment by Yimien** [comment]
![image](https://github.com/user-attachments/assets/56b6b31e-a096-4945-b886-dcf6e3307141)
在README已经说明了，标签的匹配规则修改了，就是你说的那样需要 #标签(空格)。
主要是为了能够正确识别超链接而进行的修改。

**Comment by chenxuan520** [comment]
你好,我fork了你的仓库进行更改,但是更改点为
![image](https://github.com/user-attachments/assets/f9acc312-4ddf-4b51-bdde-1c1030d1307b)
但是出现了下面的问题(使用通过github action编译生成的包,字节放入plugin目录),在打开插件按钮的时候
![image](https://github.com/user-attachments/assets/2ba102d6-97bf-40da-803e-93bb0a919796)
是编译还有什么额外需要做的去消除这个问题吗

**Comment by Yimien** [comment]
不太清楚啊，你有尝试过直接在编辑器编译的包吗？好像一直有人提到直接下载github的包到思源插件下会出现一些不知道什么原因的Bug

**Comment by Yimien** [comment]
我刚刚研究了下，目前是算是找到了能识别不以空格结尾的标签的方法了，虽然不完善还有一些漏洞，不过对于我来说影响不大，我下次更新上去。
毕竟说实在的，我也不习惯最后一个标签一定要加空格

**Comment by chenxuan520** [comment]
> 不太清楚啊，你有尝试过直接在编辑器编译的包吗？好像一直有人提到直接下载github的包到思源插件下会出现一些不知道什么原因的Bug

我试过在本地进行编译也是一样的问题,然后才用action试一下的,action也不行,弄了挺久没弄好😭.不确定是否是node和pnpm版本的问题(action的版本编译出来的无法使用)
主要是之前的标签无法准确识别,之前的数据又比较多,所以想要改善一下,不过您改了的话就期待您的下一次更新啦
