### ISSUE TITLE
同步失败，显示“暂无新数据”

### ISSUE THREAD

**Issue by RotterL** [Yimien/plugin-memos-sync-helper#14]
插件版本0.2.0，memos服务版本0.22.3，配置正确，但似乎无法同步
![image](https://github.com/user-attachments/assets/a15c7472-9639-4745-a794-6f25ff66af2e)
多次测试都始终显示“暂无新数据”

**Comment by Yimien** [comment]
昨天新增了标签过滤，看看你的标签过滤配置的是不是正确的

**Comment by RotterL** [comment]
> 昨天新增了标签过滤，看看你的标签过滤配置的是不是正确的

配置的是“同步所有数据”，并且尝试了其他选项，都显示“暂无新数据”

**Comment by Yimien** [comment]
我这里试过是可以同步数据，你确定有需要同步的数据吗？或者有没有动过上次同步时间？如果还有问题的话，开调试模式看一下日志

**Comment by RotterL** [comment]
我确定有需要同步的数据，并且我打开了调试模式，将上次同步时间锁定在一年前，但是始终无法成功同步。控制台输出如下：
![image](https://github.com/user-attachments/assets/2876eeed-b0b8-4087-bb39-99168001fc10)

**Comment by Yimien** [comment]
我临时打个包，你安装到插件目录下，再开调试模式同步一下，我看看是不是标签过滤掉了
[package.zip](https://github.com/user-attachments/files/16321189/package.zip)

**Comment by RotterL** [comment]
您好，我将上述文件解压到插件目录，替换了plugin-memos-sync-helper目录下的内容，再次同步时还是相同的结果，无法获取memos内容。
控制台输出如下：
![image](https://github.com/user-attachments/assets/b6041be2-58f5-4b3c-a58d-1ae4aaf512d2)
我的设置信息如下：
![image](https://github.com/user-attachments/assets/3d824fc3-2242-4dad-98b6-a7b8887a1000)
![image](https://github.com/user-attachments/assets/101b8a59-f04e-41b1-963a-f2995dfe630e)
![image](https://github.com/user-attachments/assets/d9644d19-f1b4-46a5-beea-807e31a20cdc)
![image](https://github.com/user-attachments/assets/77975590-981f-484b-ae67-d660cae2be90)

**Comment by Yimien** [comment]
你现在用的插件还是原来的，不是我发给你的，先删掉原来的，再把我给你的放进去

**Comment by Yimien** [comment]
使用前记得先禁用再启用

**Comment by RotterL** [comment]
我在思源集市中卸载了原插件，然后将您发的文件解压到插件目录，改名为plugin-memos-sync-helper, 并且还重启了思源，然后在设置中启用插件，我想已经确认已经使用您发我的版本替换了，但是没有变化，是不是我漏掉了什么步骤？

**Comment by Yimien** [comment]
不是看效果，我只是加了日志输出，没有确定问题的时候，不会去动功能的

**Comment by Yimien** [comment]
如果插件正确的话，日志输出这里会变成这样
![image](https://github.com/user-attachments/assets/cce881f6-bc22-47f0-b689-c95a79094f63)

**Comment by RotterL** [comment]
哦哦，我看到区别了，日志中加了标签过滤结果：
![image](https://github.com/user-attachments/assets/4f87f361-424e-49a6-8aba-2ecc2f2a8262)

**Comment by Yimien** [comment]
看日志就是没有可以更新的数据啊

**Comment by Yimien** [comment]
不然你下一下上个版本，看看能不能更新

**Comment by RotterL** [comment]
按照我现在这个设置，是不是应该所有的memo都应该被同步过来？
但是我尝试新建memo都不行。

**Comment by Yimien** [comment]
是没错

**Comment by Yimien** [comment]
我现在用的memos版本和你一样，但我这里是正常的，所以需要排查一下原因

**Comment by Yimien** [comment]
你有试过新建一个干净的思源空间来调试吗？

**Comment by RotterL** [comment]
还没有，我再试试

**Comment by RotterL** [comment]
刚试过了，新建的工作空间也不行，那会不会是我memos的问题，我再排查排查吧，感谢您的帮助

**Comment by Yimien** [comment]
你试一下这个包，我想看一下从服务器能不能拉到数据
[package.zip](https://github.com/user-attachments/files/16321372/package.zip)

**Comment by RotterL** [comment]
这个是没拉到数据的意思吗：
![image](https://github.com/user-attachments/assets/2ed398da-de8b-4a15-9af6-88b40b1e61c6)

**Comment by Yimien** [comment]
对，因为第一个日志输出这里是直接调memos 的 api，没有做任何的过滤，这里获取不到数据的话，就代表着你的服务器没有通过api输出任何数据出来

**Comment by Yimien** [comment]
这个可能就不是插件的问题，你可以尝试用一些接口测试工具，去测试一下能不能通过memos的这个api获取数据，这个属于服务端的问题了，毕竟插件想要同步数据，但服务端没给，那死活是同步不了的

**Comment by RotterL** [comment]
好的，谢谢，我去试试

**Comment by RotterL** [comment]
我发现通过ip：端口的形式是可以同步的，但是memos加了一层反代之后，用域名访问就不行了（关闭了服务端防火墙也不行），总之应该不是插件的问题，谢谢大佬花时间解答

**Comment by Yimien** [comment]
好的，问题能够解决就行
