### ISSUE TITLE
tag 无法识别

### ISSUE THREAD

**Issue by chenxuan520** [Yimien/plugin-memos-sync-helper#15]
![图片](https://github.com/user-attachments/assets/e7e422fc-d537-4d0e-bdde-465d05699e05)
- 升级到最新的插件版本之后,重新获取memos的数据,出现tag全部没有识别的问题,应该是 #tag# 前面没有加上空格的原因,和手动加上空格后被识别为tag

**Comment by Yimien** [comment]
什么意思

**Comment by chenxuan520** [comment]
![图片](https://github.com/user-attachments/assets/708bd540-ab1a-4f97-8765-10003556fe54)
这是在 # 前面加了空格的效果,是被思源识别为tag,但是同步过来的文本思源是作为普通文本而不是tag的

**Comment by Yimien** [comment]
你直接说一下操作步骤、预期结果、实际结果吧，这样我不知道你想要什么效果

**Comment by chenxuan520** [comment]
操作步骤是
1. 更新最新的版本之后,点击思源同步memos的按钮
2. memos中有一条内容为下面的笔记内容
```
忽然想到，刻舟求剑也许不像我们想得那么蠢，一样珍贵的东西掉进水里所不能舍命去捞，又觉得颇为惋借，此种心境下，在木船上刻—道记号大概是最好的纪念了，既纪念拥有也纪念失去，深知无常，却又情深义重，如果是我，大概也想不到更好的花方式了。
#刻舟求剑
```
3. 然后预期的效果是下图的样子,点击 `刻舟求剑` 后触发搜索这个tag的界面
![图片](https://github.com/user-attachments/assets/63417030-5c0c-4ae5-a66d-42d2a2bf11ec)
![图片](https://github.com/user-attachments/assets/3484949a-c64b-4b8f-a34d-7e676ef417aa)
4. 实际的效果是下图,且点击 `刻舟求剑` 后没有任何反应(因为思源识别成为普通文字了)
![图片](https://github.com/user-attachments/assets/f11fe0d9-7365-47f0-9d29-1cb4a3912ed8)

**Comment by Yimien** [comment]
> 操作步骤是
> 
> 1. 更新最新的版本之后,点击思源同步memos的按钮
> 2. memos中有一条内容为下面的笔记内容
> 
> ```
> 忽然想到，刻舟求剑也许不像我们想得那么蠢，一样珍贵的东西掉进水里所不能舍命去捞，又觉得颇为惋借，此种心境下，在木船上刻—道记号大概是最好的纪念了，既纪念拥有也纪念失去，深知无常，却又情深义重，如果是我，大概也想不到更好的花方式了。
> #刻舟求剑
> ```
> 
> 3. 然后预期的效果是下图的样子,点击 `刻舟求剑` 后触发搜索这个tag的界面
>    ![图片](https://private-user-images.githubusercontent.com/77540051/350777697-63417030-5c0c-4ae5-a66d-42d2a2bf11ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NzU1NTQsIm5iZiI6MTcyMTU3NTI1NCwicGF0aCI6Ii83NzU0MDA1MS8zNTA3Nzc2OTctNjM0MTcwMzAtNWMwYy00YWU1LWE2NmQtNDJkMmEyYmYxMWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDE1MjA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZWIxNzE4YTA3ZDNkMTk4MzE1NzI5NDI0NjRhMzJhNjRmYmEyODM2MzY1ZWRkYjA0NTkzZDc4YjAyMzJkZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UlEk4oS5fgGlFJAB4wCzvc6M38NoN3kbL2DwJs7uvlY)
>    ![图片](https://private-user-images.githubusercontent.com/77540051/350777874-3484949a-c64b-4b8f-a34d-7e676ef417aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NzU1NTQsIm5iZiI6MTcyMTU3NTI1NCwicGF0aCI6Ii83NzU0MDA1MS8zNTA3Nzc4NzQtMzQ4NDk0OWEtYzY0Yi00YjhmLWEzNGQtN2U2NzZlZjQxN2FhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDE1MjA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MzdkM2RiYjZmZjA1NjFiOWE1ZmRjMGE5ZDkzZGNmMWY1ZmE1MTY4YmQ2YTEzYmEwZGMzM2FjOWViMzU3NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kVKoxHhGFZeum0G-T33LdxGt3e9YL309n0cAgISxEZc)
> 4. 实际的效果是下图,且点击 `刻舟求剑` 后没有任何反应(因为思源识别成为普通文字了)
>    ![图片](https://private-user-images.githubusercontent.com/77540051/350777815-f11fe0d9-7365-47f0-9d29-1cb4a3912ed8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NzU1NTQsIm5iZiI6MTcyMTU3NTI1NCwicGF0aCI6Ii83NzU0MDA1MS8zNTA3Nzc4MTUtZjExZmUwZDktNzM2NS00N2YwLTlkMjktMWNiNGEzOTEyZWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDE1MjA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZGQ4ZjRlZDAyOWM2NWI0MWNlZDk3MjBhODFiZWI0NmYzMDJmMmZhMDc0MWZlMTYyYWY2YzBlMTZhM2RiY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WWRviGUGS13YZMtDkfkWUfIJH6tGEu_A9uKsWpMAtvY)

好，我明天看一下是什么问题

**Comment by chenxuan520** [comment]
这个问题似乎是手机端出现的,我厂是使用docker 浏览器端是正常的

**Comment by Yimien** [comment]
我这里显示一切正常，你思源手机端有打开支持输入行级标签语法的开关吗
![image](https://github.com/user-attachments/assets/acb03a1d-c88c-4217-a01e-c1ec6cfc36ed)
![image](https://github.com/user-attachments/assets/ccc6de5c-0132-4c32-92b2-0f41f24bb087)

**Comment by chenxuan520** [comment]
> 我这里显示一切正常，你思源手机端有打开支持输入行级标签语法的开关吗 ![image](https://private-user-images.githubusercontent.com/42413155/350833395-acb03a1d-c88c-4217-a01e-c1ec6cfc36ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDUwNjcsIm5iZiI6MTcyMTY0NDc2NywicGF0aCI6Ii80MjQxMzE1NS8zNTA4MzMzOTUtYWNiMDNhMWQtYzg4Yy00MjE3LWEwMWUtYzFlYzZjZmMzNmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDEwMzkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMjVjNGY3MGE3NWJlODM1YjM0M2ZlMGM0ZGU0YzBkNjhhN2FlMzk1OTA4NTA3NDkxNWRmOWNkYTU5MWIzODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aFZZrQvZ0xd3rw-7dKq-Jo1hoivG7Ur1tP-Fl6Q8JWA) ![image](https://private-user-images.githubusercontent.com/42413155/350834331-ccc6de5c-0132-4c32-92b2-0f41f24bb087.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDUwNjcsIm5iZiI6MTcyMTY0NDc2NywicGF0aCI6Ii80MjQxMzE1NS8zNTA4MzQzMzEtY2NjNmRlNWMtMDEzMi00YzMyLTkyYjItMGY0MWYyNGJiMDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDEwMzkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZWU1YmJjOTBiNGJlZmIwMmNhNTM2M2I4Mzc0NTg0MTgwMDEzMzFhYWZkMjJlMTAzZDkxMTlkOWQ2NTNjYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W8x10u2UnBVA4mFFZzn2KYPiU9qCJI8NGXNg3ODilC0)

打开这个设置后正常了,不过手机这个设置在app端找不到,需要使用手机私服去打开电脑浏览器端去更改选项
