### ISSUE TITLE
更新memos笔记更改而不是重复

### ISSUE THREAD

**Issue by chenxuan520** [Yimien/plugin-memos-sync-helper#16]
# 说明
- 当memos笔记更新时候(比如更改了可见的方式),插件不会更改原有的笔记内容,而是增加一条内容类似的,预期应该是更改原来已经同步的内容
# 复现
1. 更改前
![image](https://github.com/user-attachments/assets/a884f947-a7f5-4766-8e28-a945fbb62977)
2. 更改后再进行同步,得到得到下面,预期应该直接更改旧的或者直接删除旧的
![image](https://github.com/user-attachments/assets/65a7d0aa-ffb4-4669-a6d5-1dfa7a90b72c)
- 这两条笔记的id是一样的,只是updatetime变化了,可不可以监测到旧的ID时候直接删除相同笔记中旧的,或者直接更新替换

**Comment by Yimien** [comment]
![image](https://github.com/user-attachments/assets/762307fd-7e1f-4e09-a245-6c0a4ebda420)
我这里试过了，会自动删除旧的啊

**Comment by chenxuan520** [comment]
memos 版本是 0.21.0 , siyuan docker端是 3.0.9
这是memos的debug日志,高亮的是memos的id,看起来是绞车道这个block了,但是没有执行删除
![image](https://github.com/user-attachments/assets/d7df5870-46b8-49c8-8025-d693000c980f)

**Comment by chenxuan520** [comment]
GitHub编译的包还是无法直接使用,感觉主要问题是编译的时候这两个包没有被导出,导致config不存在,本地编译也是一样的问题,能提供一下 pnpm和nodejs的版本吗
版本信息为pnpm 9.0.0, node 22.4.0构建方式为
1. git clone https://github.com/Yimien/plugin-memos-sync-helper
2. pnpm install
3. pnpm build
![image](https://github.com/user-attachments/assets/e1a937fe-75b9-472e-8df6-c6edeb2e57d7)

**Comment by Yimien** [comment]
> GitHub编译的包还是无法直接使用,感觉主要问题是编译的时候这两个包没有被导出,导致config不存在,本地编译也是一样的问题,能提供一下 pnpm和nodejs的版本吗 版本信息为pnpm 9.0.0, node 22.4.0构建方式为
> 
> 1. git clone https://github.com/Yimien/plugin-memos-sync-helper
> 2. pnpm install
> 3. pnpm build
>    ![image](https://private-user-images.githubusercontent.com/77540051/356069014-e1a937fe-75b9-472e-8df6-c6edeb2e57d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTE3OTUsIm5iZiI6MTcyMzA5MTQ5NSwicGF0aCI6Ii83NzU0MDA1MS8zNTYwNjkwMTQtZTFhOTM3ZmUtNzViOS00NzJlLThkZjYtYzZlZGViMmU1N2Q3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA0MzEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjYWI3ODIxMzE5MTJkYjc0YTMyMWZhYWQzZjJmZTdlZjJmYTczM2FhYzUxNjRhYTUyZTZmZTVhMTMzMTBmZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qdxs2e6_GkeyqkdQQ9ciJyoDfblRzZjh1H57JeIVcEk)

pnpm 8.15.5
node v20.11.1

**Comment by Yimien** [comment]
> memos 版本是 0.21.0 , siyuan docker端是 3.0.9 这是memos的debug日志,高亮的是memos的id,看起来是绞车道这个block了,但是没有执行删除 如果还需要的话我可以提供其他信息 ![image](https://private-user-images.githubusercontent.com/77540051/355908386-d7df5870-46b8-49c8-8025-d693000c980f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTE3OTUsIm5iZiI6MTcyMzA5MTQ5NSwicGF0aCI6Ii83NzU0MDA1MS8zNTU5MDgzODYtZDdkZjU4NzAtNDZiOC00OWM4LTgwMjUtZDY5MzAwMGM5ODBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA0MzEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YjQ3MDQ2ZmE4MjkzNjE1Njc0MTdhNmY1NjExNmQ2ZTdjMGYyMjg3N2I1NGM0YThhMTE0ZWZhMmI5YTE4NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bnHat9CcKFqqS_cRJEEn9HiLFquMZdiOmuJL7yzHF6o)

从日志上看，整理结果只有new列表有数据，那就是做新增操作没错，如果要删掉旧数据，那应该是old有数据才对

**Comment by Yimien** [comment]
就像这样子，old有数据才会去删除，old的数据来自时间的比较
![image](https://github.com/user-attachments/assets/f16d62f0-a4f9-465a-9341-9d84e2af10c9)

**Comment by chenxuan520** [comment]
v1 和v2 版本的这个释放是不是有问题
![image](https://github.com/user-attachments/assets/73648c7e-c22c-4599-8a86-6af586d20296)

**Comment by chenxuan520** [comment]
能给出编译步骤吗,我同步到你的版本但是还是无法实现编译得到可用包的操作,是否存在一些类似env的文件不在仓库中导致无法编译,在你那里编译会出现类似的警告吗

![image](https://github.com/user-attachments/assets/0693f096-8951-47f4-a67c-048e715130b4)

**Comment by Yimien** [comment]
> v1 和v2 版本的这个地方是不是有问题,这里两边都应该是create_time吧 ![image](https://private-user-images.githubusercontent.com/77540051/356086394-73648c7e-c22c-4599-8a86-6af586d20296.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDAwMjMsIm5iZiI6MTcyMzA5OTcyMywicGF0aCI6Ii83NzU0MDA1MS8zNTYwODYzOTQtNzM2NDhjN2UtYzIyYy00NTk5LThhODYtNmFmNTg2ZDIwMjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA2NDg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MWU1YjgzZWFiZmNhNzA2NGIxNjBjZDdkNWRlNmEyOTI3YTg4YmMzMmVmNWUxYWI5OWRhYTRkMGQ1ZTI4OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SHxXtgO8BGS4l4hrG13WCFVDVR5_lJBUcMvRpDKVEug)

好像是这个问题，我改下发个版

**Comment by Yimien** [comment]
> 能给出编译步骤吗,我同步到你的版本但是还是无法实现编译得到可用包的操作,是否存在一些类似env的文件不在仓库中导致无法编译,在你那里编译会出现类似的警告吗
> 
> ![image](https://private-user-images.githubusercontent.com/77540051/356092824-0693f096-8951-47f4-a67c-048e715130b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDAwMjMsIm5iZiI6MTcyMzA5OTcyMywicGF0aCI6Ii83NzU0MDA1MS8zNTYwOTI4MjQtMDY5M2YwOTYtODk1MS00N2Y0LWE2N2MtMDQ4ZTcxNTEzMGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA2NDg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNTFiYjk3YzRmMDk1MTE4Y2EyM2Q3M2QyYmM5MzhhYWU4MzZlMDE2NzM1NGRhZDY1NTkyYThlY2Y0OTU5ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HMgwpTZjYVJkMfC0jhL-AS3G5dfllUsYgRIzC3Yu88U)

编译的话，没报什么错
![image](https://github.com/user-attachments/assets/001f92a8-0026-4b4d-8d1a-c644328874e0)

我都是根据这个说明来做处理的
https://github.com/siyuan-note/plugin-sample-vite-svelte/blob/main/README_zh_CN.md

**Comment by chenxuan520** [comment]
![image](https://github.com/user-attachments/assets/1b47f2e7-6d7f-46d6-b64d-417522068faf)
知道问题了,编译时因为没有运行这个命令才使得编译得到文件无法使用
