### ISSUE TITLE
如何复位同步记录

### ISSUE THREAD

**Issue by jixintangen** [Yimien/plugin-memos-sync-helper#18]
### 在哪些情况下需要此功能？

当修改了同步配置，希望重新拉起同步，目前好像不可以

### 描述最优解决方案

或许已经有了只是我还不会用，不知道怎么复位，并重新同步

**Comment by Yimien** [comment]
先校验一下看看是否能访问服务器，正常情况下就可以同步了，不行的话可以通过修改【过滤配置】的【上次同步时间】，插件会以上次同步时间为起始时间将你的数据进行同步到思源。

**Comment by Yimien** [comment]
后续有反馈再开启
