### ISSUE TITLE
同步报错：TypeError: url.endsWith is not a function

### ISSUE THREAD

**Issue by 5kyfkr** [Yimien/plugin-memos-sync-helper#19]
### 操作步骤

如下图，校验通过但是同步报错
![image](https://github.com/user-attachments/assets/162381da-77a6-4f63-ba63-f1425aa815a6)

![image](https://github.com/user-attachments/assets/e69cba25-9d31-4f58-87d9-a36fd7ff753b)

![image](https://github.com/user-attachments/assets/627dcfad-36a1-44b5-a84e-067d2ee0af6b)

### 预期结果

正常同步

### 实际结果

有报错

### 插件版本

v0.2.5

### Memos版本

0.23.0

### 思源笔记

Windows

**Comment by Yimien** [comment]
看信息是在从memos服务器获取数据的时候报的错，但是我这里测试一下没出现这个报错。

![image](https://github.com/user-attachments/assets/51ac81fa-3756-4d0a-8678-0c8ae2d73c91)

![image](https://github.com/user-attachments/assets/2847a414-7bfe-4c39-b7df-0d7640fea7b4)

![image](https://github.com/user-attachments/assets/3251d95d-bab9-42ab-8f9e-60241685b44a)

所以可能需要你那边试一下是不是服务器获取数据的问题

另外，我发现v0.23.0的接口有问题，很多返回的数据都是空的，比如资源列表、节点列表，这意味着这个版本的接口只能传输文本信息，所以如果不是非常必要，建议还是先退一个版本，后面再看看情况。

PS.memos的版本最好不要追latest，很容易出问题，追stable就足够了，但事实上我现在压根就不让memos自动更新

**Comment by 5kyfkr** [comment]
我用0.22.5试了似乎也报一样的错，我半年前刚0.22的时候还是可以的，奇了怪了

**Comment by 5kyfkr** [comment]
找到问题了，是用了这个js导致的[https://ld246.com/article/1726193300954](url)
