### ISSUE TITLE
代码块同步问题

### ISSUE THREAD

**Issue by Yimien** [Yimien/plugin-memos-sync-helper#2]
试了最新的一版，发现了问题所在，当你第一次使用该插件的时候，选同步方案为：同步为单独的文档，然后文档路径此时是不带✳️的，然后不输入文档路径去点同步就不会同步数据下来！
# 新问题
## Memos原文如下
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/40713819/bb2ffc96-936b-405b-b653-c586405d8373)
## 同步过来后如下
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/40713819/a8ae0ac9-ba4b-4a0b-a1da-5ad2f0ad3391)
我看了下同步到思源本地的代码块基本上都是这种问题

_Originally posted by @WyInnovate in https://github.com/Yimien/plugin-memos-sync-helper/issues/1#issuecomment-2146388741_

**Comment by Yimien** [comment]
已修复

**Comment by WyInnovate** [comment]
@Yimien 
问题仍然存在，我给你贴一下控制台日志，你看一下就明白了
# 控制台日志
## 原始内容
### Memos内容
```
#静态网站 
# 升级 http 请求
```
升级 http 请求是可以的，主要是这一行 add_header Content-Security-Policy upgrade-insecure-requests;

solo反代内容：
location / {
        proxy_pass http://192.168.50.184:8100;
        add_header Content-Security-Policy upgrade-insecure-requests;
        proxy_set_header  Host $http_host;
        proxy_set_header  X-Real-IP $remote_addr;
        client_max_body_size  10m;
}
```
```
## 处理后内容
### 第一部分
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/40713819/d6a8a7a4-621c-496f-8677-3036b171c73d)
第一部分多了```
### 第二部分
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/40713819/ee738fb0-69e4-43a4-9bea-114b13391348)
第二部分多了前两行，然后```后少了个回车

有一部分上传的截图忘记打码了，麻烦删一下截图吧，我重新上传了图

**Comment by Yimien** [comment]
你笔记的内容发一下，我看看是哪里的处理有问题

**Comment by Yimien** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/42413155/ccf48a70-13bc-4cca-b43a-a0665ccf67c7)
我这里是正常的啊，你确定版本对吗？

**Comment by Yimien** [comment]
原先这里出的问题是因为我在处理内容的时候，忽略了代码块的开头```和结尾```是一样的字符，导致代码块被拆分成两个块，但现在已经改用index做结束标志了，不应该还有这个问题才对

**Comment by WyInnovate** [comment]
> 原先这里出的问题是因为我在处理内容的时候，忽略了代码块的开头和结尾是一样的字符 ```，导致代码块被拆分成两个块，但现在已经改用index做结束标志了，不应该还有这个问题才对

@Yimien 
Memos版本v0.22.1 思源笔记版本v3.0.17
[示例.md](https://github.com/user-attachments/files/15544994/default.md)
示例文件上传了

**Comment by WyInnovate** [comment]
@Yimien 好像我从github上下载然后放到插件文件夹里不会生效，我重新从插件集市下的1.0.2版本没问题，issue可以关了

**Comment by Yimien** [comment]
好
