### ISSUE TITLE
更新到v0.23.0后无法下载图片

### ISSUE THREAD

**Issue by yejianrui** [Yimien/plugin-memos-sync-helper#20]
### 操作步骤

使用插件内的“0.22.1以上”模式，文字可以正常同步，图片无法下载。已在memos中设置了数据库存储模式与本地模式都无法下载。

### 预期结果

未更新memos前可正常同步图片及文字。

### 实际结果

![image](https://github.com/user-attachments/assets/b1ed0b7d-3bc0-4060-a357-3b2db952970c)

### 插件版本

V0.2.5

### Memos版本

V0.22.1

### 思源笔记

Windows

**Comment by Yimien** [comment]
已修复
