### ISSUE TITLE
插件无法传输图片到思源

### ISSUE THREAD

**Issue by loonghfut** [Yimien/plugin-memos-sync-helper#21]
### 操作步骤

再memos上上传图片后，点击思源中memos插件同步

### 预期结果

memos上的图片正常被传输到思源笔记里

### 实际结果

文字可以传输，但图片无法显示，且有时会传输两次相同的文字

### 备注

环境 docker版最新思源

### 插件版本

0.2.6

### Memos版本

0.22.5

### 思源笔记

Docker

**Comment by Yimien** [comment]
我这里正常，你可以尝试一下切换一下版本选项再切换回来，因为这次更新动了一些数据配置，可能需要重新选择一下版本。还不行的话，你可以开一下调试模式截图一下日志

**Comment by loonghfut** [comment]
感谢回复，
是的，新版本的配置变了，修改版本选项后，可以使用了。
打扰了，抱歉。
