### ISSUE TITLE
docker版本无法点击校验按钮，无法使用

### ISSUE THREAD

**Issue by leeima** [Yimien/plugin-memos-sync-helper#3]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/84554107/96c013ed-db18-4bab-8133-019496748e13)

**Comment by Yimien** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/42413155/c340ca3e-9bc8-4066-9734-1545bf13f702)
我这里一切正常，开调试模式看一下控制台日志

**Comment by Yimien** [comment]
好像是新版api接口不支持吧

**Comment by Yimien** [comment]
这个好像只能在服务端处理，现在如果要用新版本memos的话，恐怕只能用思源的客户端，docker端我应该是解决不了，在开发的时候我也只能在客户端调试，实在要用docker版的话，只能用旧版本的memos了。
不过说实在的，新版本的memos并不好用，api调用起来也是很麻烦

**Comment by leeima** [comment]
> 这个好像只能在服务端处理，现在如果要用新版本memos的话，恐怕只能用思源的客户端，docker端我应该是解决不了，在开发的时候我也只能在客户端调试，实在要用docker版的话，只能用旧版本的memos了。 不过说实在的，新版本的memos并不好用，api调用起来也是很麻烦

好的，谢大佬

**Comment by chenxuan520** [comment]
这个docker新版api无法使用的原因是什么啊?

**Comment by Yimien** [comment]
> 这个docker新版api无法使用的原因是什么啊?或许我可以帮上忙

印象中好像是因为跨域请求，只要通过浏览器去调用都会报错，但是在思源客户端调用就不会

**Comment by chenxuan520** [comment]
跨域问题的话,旧版本的api是响应加了跨域头,但是新版本的api没有加吗,有点神奇,找时间我研究一下

**Comment by Yimien** [comment]
> 跨域问题的话,旧版本的api是响应加了跨域头,但是新版本的api没有加吗,有点神奇,找时间我研究一下

可能吧，新版的api和旧版的差别很大，漏了或者特意不加也是有可能的

**Comment by Yimien** [comment]
> 跨域问题的话,旧版本的api是响应加了跨域头,但是新版本的api没有加吗,有点神奇,找时间我研究一下

这个问题我想应该不用研究了，我今天看了下，最新版的memos貌似修复这个问题了，我刚刚用docker试了下，不会报错了
