### ISSUE TITLE
数据排序 疑问🤔

### ISSUE THREAD

**Issue by WyInnovate** [Yimien/plugin-memos-sync-helper#4]
设置里说根据更新日期进行排序，但是为啥我这当日的排序还是有问题的？要逼死强迫症了
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/40713819/16588df9-3059-4620-8ef9-dafedeca7f89)

**Comment by Yimien** [comment]
在写入前会对数据进行排序，如果是内容块的话一切正常，但是文档的话，但是不知道为什么，顺序就是会乱

**Comment by Yimien** [comment]
可能是异步操作的原因，这个确实处理不了，说实在的，我也觉得很难受，但是，一想我又不用这种模式，觉得也还是能接受的😅
