### ISSUE TITLE
集市的包好像还是0.11没有更新？

### ISSUE THREAD

**Issue by zhuxiucai** [Yimien/plugin-memos-sync-helper#5]
这个和github 不同步更新的吗？

**Comment by Yimien** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/42413155/76399e6f-472c-4eb2-aa07-1b4e6f5f7ab3)
同步啊，上架集市了还能不同步吗

**Comment by WyInnovate** [comment]
@zhuxiucai  0.14版本了

**Comment by Yimien** [comment]
@zhuxiucai 
我看到更新了，你确定没有吗？
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/42413155/8e8c7184-1d93-466c-9018-a5603ff71303)

**Comment by zhuxiucai** [comment]
<img width="1674" alt="image" src="https://github.com/Yimien/plugin-memos-sync-helper/assets/10626025/3b211f24-db57-4877-9c2d-196ece37cbb2">
好神奇！
绝了

**Comment by Yimien** [comment]
> <img alt="image" width="1674" src="https://private-user-images.githubusercontent.com/10626025/337186988-3b211f24-db57-4877-9c2d-196ece37cbb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjY3NDQsIm5iZiI6MTcxNzY2NjQ0NCwicGF0aCI6Ii8xMDYyNjAyNS8zMzcxODY5ODgtM2IyMTFmMjQtZGI1Ny00ODc3LTljMmQtMTk2ZWNlMzdjYmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA5MzQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjOGE2ZjdmZDZlOTg5ZTY0YTg4MmE3MDIwNDZmMTM5YmRmZGIwYmYyZDdhNjU5ZWNjOWNmNmFjYzkyYWE2NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QKCyI_A0oTbw9Ih6eDG7egnEXU0SlxS1Xx7Kzp_InY8"> 好神奇！ 绝了

插件集市上的版本是多少？如果版本高的话那应该是更新的检测有问题，如果版本一样的话，那就插件的更新拉取有问题，但不管是什么问题，都需要D大他们去看看，当然，如果卸载重装能解决的话，也还行，毕竟代码这东西，偶尔抽风一下也是能理解的
