### ISSUE TITLE
图片无法下载到思源笔记中

### ISSUE THREAD

**Issue by netdog2019** [Yimien/plugin-memos-sync-helper#6]
服务器上是0.22.1版本，Memos 同步助手0.1.4版，思源笔记是PC端最新版，不知道是哪里的原因？
原来的同步助手有选择资源下载模式，选择uid就可以。不知道是不是bug还是我操作问题，感谢大神~~
![1717728397276](https://github.com/Yimien/plugin-memos-sync-helper/assets/49815951/53e14877-9dfa-40d7-a12b-7eb3ea3ec6fe)

**Comment by Yimien** [comment]
之前的资源下载模式是因为那个时候memos经常换资源路径，也不是所有人都追新，所以出的一个兼容方案，去除是因为v2接口有出相关的api，虽然在我开发的时候不知道为什么用不了，但是没想到memos又换资源路径了。
至于这个问题，有点离谱，一方面跟memos换了资源访问路径关，另一方面貌似还跟思源的资源保存路径有关。
资源下载路径这个功能可能不会再出，会改成用版本选择，另外思源的资源保存路径会开放出来自定义。

**Comment by netdog2019** [comment]
感谢大佬解惑，那0.22.1版本中的图片还有什么办法能同步到思源么？我用老版本的同步助手好像又链接不上。感谢感谢。

**Comment by netdog2019** [comment]
0.18版本可以了，感谢大佬。我猜测可能出的问题，供大佬参考。我看了一下assets\memos目录里有那些没法显示的图片占用，只有47字节，但是每张图片都在，所以及时我删除了相应日期的笔记，但是图片因为在assets\memos里已经有了占用，所以无法重新下载同样名字的图片覆盖，因此及时我删除相应日期笔记再次同步，也还是无法把图片同步下来。只要我把相应名字的图片文件删除（47自己的图片，无法显示，但是有这么个文件在assets\memos里），就可以同步了。

**Comment by Yimien** [comment]
老版本的只支持到0.21，除非你的memos 版本在0.21以下，不然没必要用老版本的了
要同步0.22.1的话，在插件里面选择对应的版本就行，如果还不能显示：
一是清理旧图片；
二是修改资源保存路径；
三是修改上传的图片名称；

我在测试的时候，基本上调整这三个就可以，至于具体原因，以后再看吧

> 感谢大佬解惑，那0.22.1版本中的图片还有什么办法能同步到思源么？我用老版本的同步助手好像又链接不上。感谢感谢。
