### ISSUE TITLE
检查了很多遍设置，但是一直同步失败

### ISSUE THREAD

**Issue by tianya778** [Yimien/plugin-memos-sync-helper#7]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/a8bbce92-17f6-447e-afad-83d8d7a9ffed)

![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/53f9192e-035d-44ae-a784-23e0aeefa18f)

我新建了一个思源笔记的库，然后重新安装了memo同步插件，重新设置；token校验是正确的，但是一直无法同步。

**Comment by Yimien** [comment]
1. 检查一下每个选项卡是否有带*的没有配置，或者配置的数据不符合要求，比如末尾不能有 '/'或者必须以‘/’开头之类的
2. 详细可以开调试模式看一下控制台输出

**Comment by Yimien** [comment]
已经发版了，等插件市场同步吧，更新后你再试试，如果有什么不对再说，没问题也告知一下，我好关掉

**Comment by tianya778** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/ccb16380-7668-46d6-87f9-560f543f3481)
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/5f111cb9-7ba3-4fed-9c19-c4f5188559ca)
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/fc97cb4d-bd02-42bc-b26f-a5de75fe63be)
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/cc156382-e956-4f32-a66b-3e3db0c35519)
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/986cb7c9-5689-43c5-8070-8113e3b0eb6f)

上面是我的配置详情，我的同步还是失败的:(

**Comment by Yimien** [comment]
插件今天有更新吗，更新后再看看

**Comment by tianya778** [comment]
已经更新过了，上面的截图是更新之后尝试的。

**Comment by Yimien** [comment]
不对，今天更新的时候我把上次更新忘记隐藏的测试功能按钮给隐藏了，现在你的截图还在，明显是版本不对，而且新版会提示是哪个部分检查没通过

**Comment by tianya778** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/a7cc8818-8f9b-4c43-ab44-b46e38dd5851)

我更新之后并未退出软件，刚刚退出软件重新打开之后有了提示了，提示文档路径错误，但我的路径设置应该么有问题:( 
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/6869743b-c422-430d-8626-6bf97e6a832b)

**Comment by Yimien** [comment]
我知道问题，你文档路径填了，但可能是 / 没加开头或者后面多加了，不过正常情况下是应该是在必填的时候才检查了，我这里处理一下，再发个版

**Comment by Yimien** [comment]
发版了，等插件市场同步更新后再试试，理论上应该没问题了

**Comment by Yimien** [comment]
对了，能不能发一下你的文档路径是怎么配置的，我好看一下是不是这里的检查有问题 @tianya778

**Comment by tianya778** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/45dce149-9bf9-4c40-8aaa-a984cf7783f7)
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/154526bd-c7fb-43b5-8a44-59f205e52a15)
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/96246018-d3b0-4926-848f-528d58b1f7fd)
插件市场还没更新，我把我的配置都给你看看。

**Comment by Yimien** [comment]
这几个地方看起来是没问题，提示也是文档路径配置出的问题，文档路径在于你将同步方案切换一下才会出来

**Comment by tianya778** [comment]
> 这几个地方看起来是没问题，提示也是文档路径配置出的问题，文档路径在于你将同步方案切换一下才会出来

那我的测试需要切回去原来的笔记数据测试吗？

**Comment by Yimien** [comment]
你可以先用这个测，没问题再回去同步，不碍事，主要是你配置的那个文档路径为什么会报不通过，你文档路径是怎么写的？

**Comment by tianya778** [comment]
我感觉我就正常配置的，之前同步成功过一次；后面我忘了我设置啥了，就一直同步失败。
我文档路径怎么检查，或者截图哪些东西给你看？这些名词我不太熟悉，你可以把具体的操作步骤告诉我，我截图给你排查。

**Comment by tianya778** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/382a1ea0-0eed-43b0-900b-7c8f6e0d12c3)
现在的提示变更为主题路径了

**Comment by tianya778** [comment]
同步成功了🤣
md我知道我哪里错了：
因为我的dailynote是创建在日记这个笔记本下，然后我选的是同步到dailynote
笔记本我选择了日记，后面的主题路径还需要再设置日记本下的dailynote
也就是主题路径还需要设置为：`/daily note`

**Comment by Yimien** [comment]
呃，不是，这里不是这么理解，这里出问题的确是因为主题路径没有配，主要是插件配置检查这一块比较麻烦，经常会忘前提条件。这里出问题的原因是，因为主题路径它是非必填的，但是它的填写需要匹配 `/` 开头的规则，所以加了一层校验，但是没有匹配说只有在打开识别双链开关，并且主题路径不为空时才去匹配的规则，所以就导致了，你打开了开关，没填写主题路径，它在检测的时候发现主题路径没有以 `\` 开头，所以判断不通过，是这个原因。
daily note 模式的保存路径是直接读你同步笔记本的配置的，和主题路径无关。主题路径是用于在识别双链时，如果你链接的文档不存在，它会自动创建在主题路径下面，如果你主题路径没有填，那它就是直接新建在同步笔记本下面。

**Comment by tianya778** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/95f3762a-45f9-406c-b03a-2cfa17695cec)
同步的问题解决了，但是现在的一个新问题是：同步完成之后没有自动更新时间，再次同步的时候，我前面的笔记同步重复了，出现了两条一模一样的笔记。

**Comment by Yimien** [comment]
因为你调试模式开着吧

**Comment by Yimien** [comment]
调试模式开着默认是不会更新上次同步时间的

**Comment by tianya778** [comment]
没有，同步的时候我关闭了调试模式了。

**Comment by Yimien** [comment]
你确定？我这里是正常的

**Comment by tianya778** [comment]
确定，等我重启笔记再同步一次试试。

**Comment by tianya778** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/4ba1f225-d16b-4a0d-94ee-b3de27d961c9)
现在已经停止同步了，但还是停留在2020年。

**Comment by Yimien** [comment]
看一下调试模式

**Comment by Yimien** [comment]
这个是默认设置的时间

**Comment by tianya778** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/1970ca57-65bb-449e-9718-f4fec931aebe)
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/7324cebf-04ed-46b4-bf92-f6bb75d4f24c)
我打开了调试模式，重新同步了一次，又出现下面这个报错：
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/947ab2ff-bbd2-4504-9fb2-88519ae7dda5)
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/f594dfeb-7274-4eef-8b99-4334e532be6b)
图标处于上述状态
时间还是没有更新

**Comment by Yimien** [comment]
呃，是同步的时候会弹右上角的红框信息出来是吗？

**Comment by tianya778** [comment]
> 呃，是同步的时候会弹右上角的红框信息出来是吗？

差不多等笔记同步完登上几秒就出来了

**Comment by Yimien** [comment]
有出同步完成的提示吗？一般来说出红色提示就是代表有问题

**Comment by Yimien** [comment]
在确保调试模式开启的情况下，打开控制台，看一下操作日志

**Comment by tianya778** [comment]
> 有出同步完成的提示吗？一般来说出红色提示就是代表有问题

没有，只有红色的提示，然后状态栏的图标一直显示同步的状态，现在的截图：
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/3a6062c5-14c6-4286-ac92-e794def78e71)

**Comment by Yimien** [comment]
没有那就代表没有同步成功，只有在同步成功的情况下才会更新上次同步时间

**Comment by Yimien** [comment]
现在还是得看控制台才能知道问题

**Comment by Yimien** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/42413155/e4b33e87-4c47-4dc4-b0ba-076fb8545c1a)
开一下这个

**Comment by tianya778** [comment]
打开了，我需要截图具体的哪部分给你？
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/15b039b3-7b87-4a13-9d85-aff2054a7678)

**Comment by Yimien** [comment]
console

**Comment by tianya778** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/ce22b116-4223-43f1-913f-42979a3fe05f)

**Comment by Yimien** [comment]
点一下同步按钮，看看在哪里报错

**Comment by tianya778** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/b7740f15-4e5c-4d4d-b22a-e5f56e20bb22)

**Comment by Yimien** [comment]
这个是思源的api接口，正常不应该有问题，现在的信息太少判断不了，我临时打个包上来，你解压后丢到工作空间的插件路径，再同步看看
[dist.zip](https://github.com/user-attachments/files/15748371/dist.zip)
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/42413155/e2474991-dcc4-46e2-a522-44890778e5b4)

**Comment by tianya778** [comment]
下面是用你的版本同步的截图：
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/8ba1a0da-0e94-44ff-b562-0e2545758d4a)

**Comment by Yimien** [comment]
你把控制台向上拉一下，或者按下图把控制台放到右边拉长点
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/42413155/d0f42255-89d0-4e55-8214-29108c4ecb7b)

**Comment by tianya778** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/4c5d8365-e3a3-4681-8eb4-4fca8cbe2df4)

**Comment by Yimien** [comment]
呃，再点一次，为什么blockId会没显示值出来

**Comment by tianya778** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/3ea50c6b-c91b-4a20-ba1f-ca1456ff2b41)
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/bb76aab9-6c3c-4bd3-90bc-8f1398de721b)

**Comment by Yimien** [comment]
[dist.zip](https://github.com/user-attachments/files/15748583/dist.zip)
信息还是太少，麻烦用这个再试下，目前猜测是blockId这个值没拿到导致的

**Comment by tianya778** [comment]
ok，稍等几分钟，冲个澡🤣

**Comment by Yimien** [comment]
有点晚了，明天再看吧

**Comment by tianya778** [comment]
好的，那你明天再处理，早点休息，稍后我先把结果留言。

**Comment by tianya778** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/71315db3-ab1b-4f03-af6f-b90e30055bbd)
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/c0552d6c-c126-4681-83a7-478529023054)

**Comment by Yimien** [comment]
你看到最后那个memoId 178，翻到前面，在memoIdLinkBlockId里面找找有没对应的BlockId值

> ![image](https://private-user-images.githubusercontent.com/32615715/337893850-71315db3-ab1b-4f03-af6f-b90e30055bbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MDAyMDUsIm5iZiI6MTcxNzg5OTkwNSwicGF0aCI6Ii8zMjYxNTcxNS8zMzc4OTM4NTAtNzEzMTVkYjMtYWIxYi00ZjAzLWFmNmYtYjkwZTMwMDU1YmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDAyMjUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNGYxZGY3MGIxZjRlOGEzODlkNzRiYTBmYjVkOGE5NmE0NGZiYzg2YzY4ZGViNjM4NTQwYTE3NzI1YTU0OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-vDdhjB-2cYOxCnaGrchLYpT98Mac1hCM5XvSyHlB7Y) ![image](https://private-user-images.githubusercontent.com/32615715/337893904-c0552d6c-c126-4681-83a7-478529023054.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MDAyMDUsIm5iZiI6MTcxNzg5OTkwNSwicGF0aCI6Ii8zMjYxNTcxNS8zMzc4OTM5MDQtYzA1NTJkNmMtYzEyNi00NjgxLTgzYTctNDc4NTI5MDIzMDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDAyMjUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZWNmODY1OTQxNTA2MzEyOWJkYTE2YWI5MzY0MzFmY2RmYTY5MzA1ZjlmY2M1NGVjNjhiZmQyY2FiNDkzMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BiHcjVw1nVO2kGNu5XwRflheti_bVocoptUidX1wGbI)

**Comment by tianya778** [comment]
我这没显示出来你的图片
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/817aabc4-087a-44c6-8559-31f08535aad1)

**Comment by tianya778** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/72a3defb-ecfe-4ade-8ce8-b726bb1107d8)
如果你指的是这个的话，我没找到id178对应上的值

**Comment by Yimien** [comment]
你翻到前面，有个数据处理结果，按下图这样展开，找找看有没有id是178的
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/42413155/e6a634e2-98ba-4a37-94a9-5be07608d04f)
如果找不到，再往前，有一个获取结果，找一找有没有一个name 是 memos/178的数据
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/42413155/b4fa9f66-7827-4f4e-9466-2e809e23ede2)

**Comment by tianya778** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/7fcf9520-422e-434a-99ca-ecf30006aa7b)
我不知道为啥，我的无法展开

**Comment by Yimien** [comment]
你是在思源笔记上的控制台上看的吗？

**Comment by tianya778** [comment]
是的，思源笔记的开发者工具

**Comment by Yimien** [comment]
不清楚，简单点，重启能解决大部分的烦恼

**Comment by tianya778** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/11fa49f3-8c99-4732-b37d-b82a1724ef30)
memos 178没有

**Comment by Yimien** [comment]
后面有一个需处理的引用列表，找找看有没有 memos/178
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/42413155/23534046-221f-480b-8d08-27ba8c3f9345)

**Comment by tianya778** [comment]
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/32615715/c67a21af-a914-4cf6-895d-01e4fe8a6ff1)
找到了

**Comment by Yimien** [comment]
> ![image](https://private-user-images.githubusercontent.com/32615715/337945260-c67a21af-a914-4cf6-895d-01e4fe8a6ff1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MDUwMzEsIm5iZiI6MTcxNzkwNDczMSwicGF0aCI6Ii8zMjYxNTcxNS8zMzc5NDUyNjAtYzY3YTIxYWYtYTkxNC00Y2Y2LTg5NWQtMDFlNGZlOGE2ZmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDAzNDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMjY5ZDZjNTg2MmExYTM2NTFmNzRhMmQ5ZDIxOWU3M2FkMzZhYjMwYmYxZTczNjFlOGExNDAyOTI3ZGEzNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4de-Cp9DmLn1YV2pSijHfbIDaeB_6zfewcny6_JSUbU) 找到了

有一个好消息和一个坏消息，好消息是知道原因了，坏消息是你这条数据的问题出在评论。
你应该是在评论那里引用别的 memo，但因为插件没有对评论进行同步，所以找不到这条memo，因此无法写入导致的报错。

不打算做评论的同步是因为
1. 目前来说，我用不到评论
2. 评论的同步处理起来很麻烦

回到你这个问题，我可能会过滤掉评论的引用，只处理memo的引用

**Comment by Yimien** [comment]
这应该是新版api调整的问题，0.21的话看起来就比较正常
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/42413155/8b978b6f-17e5-4d96-8366-4ab9be13a950)

**Comment by tianya778** [comment]
> > ![image](https://private-user-images.githubusercontent.com/32615715/337945260-c67a21af-a914-4cf6-895d-01e4fe8a6ff1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MDUwMzEsIm5iZiI6MTcxNzkwNDczMSwicGF0aCI6Ii8zMjYxNTcxNS8zMzc5NDUyNjAtYzY3YTIxYWYtYTkxNC00Y2Y2LTg5NWQtMDFlNGZlOGE2ZmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDAzNDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMjY5ZDZjNTg2MmExYTM2NTFmNzRhMmQ5ZDIxOWU3M2FkMzZhYjMwYmYxZTczNjFlOGExNDAyOTI3ZGEzNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4de-Cp9DmLn1YV2pSijHfbIDaeB_6zfewcny6_JSUbU) 找到了
> 
> 有一个好消息和一个坏消息，好消息是知道原因了，坏消息是你这条数据的问题出在评论。 你应该是在评论那里引用别的 memo，但因为插件没有对评论进行同步，所以找不到这条memo，因此无法写入导致的报错。
> 
> 不打算做评论的同步是因为
> 
> 1. 目前来说，我用不到评论
> 2. 评论的同步处理起来很麻烦
> 
> 回到你这个问题，我可能会过滤掉评论的引用，只处理memo的引用

哈哈哈，找到问题就好了；其实评论这个只是心血来潮试了一下，评论对我来说也用不到。

**Comment by Yimien** [comment]
发布更新了，等插件市场同步吧。
我一开始也是自动追新的，但是当时一觉醒来，发现升到0.22后体验了一下，发现什么旧的api都失效了，编辑器的列表语法变得很奇怪，标签都没了， 所以就回退版本了。
说实话，我是没想到 memos 有种越做越差的感觉。

**Comment by tianya778** [comment]
好的，麻烦作者了。
我现在其实也在考虑是否还要使用memos，因为我更需要稳定的笔记，这些技术门槛有些时候让我担心未来的笔记数据维护🤣

**Comment by Yimien** [comment]
如果想要稳定那就不要去追求更新了，选一个稳定的版本就好，毕竟如果你现在使用没有问题，大概率以后也不会有问题。除非以后特别需要某个功能，那再去更新就好。开源软件自部署就是有这么一个好处。

**Comment by Yimien** [comment]
插件市场好像更新了，你再试试有没有问题，没问题我就关了

**Comment by tianya778** [comment]
没问题了，问题可以关闭了。

天涯

________________________________
发件人: Yimien ***@***.***>
发送时间: Sunday, June 9, 2024 2:01:31 PM
收件人: Yimien/plugin-memos-sync-helper ***@***.***>
抄送: 啊呜喵 ***@***.***>; Manual ***@***.***>
主题: Re: [Yimien/plugin-memos-sync-helper] 检查了很多遍设置，但是一直同步失败 (Issue #7)


插件市场好像更新了，你再试试有没有问题，没问题我就关了

―
