### ISSUE TITLE
请问为什么“移除了图片块布局功能”呢？

### ISSUE THREAD

**Issue by pisceswb** [Yimien/plugin-memos-sync-helper#8]
请问为什么“移除了图片块布局功能”呢？能不能给一个设置，能够允许启用该功能啊，图片很多的时候还是横排方便查看🙏

**Comment by Yimien** [comment]
核心原因是同步逻辑的修改，原先是所有的图片都在一个块中，纵向横向的调整很简单，但现在每一张图片都放至一个块中后变得不好处理；
其次是我发现思源本身可以支持这个功能，批量选中图片后，右键合并 超级块 -> 水平布局
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/42413155/0cc7835e-8f48-43c6-838d-f2cf45b0df5e)
![image](https://github.com/Yimien/plugin-memos-sync-helper/assets/42413155/4f6f0695-b97f-4b5f-9fc3-2b0514bd1e61)
我个人感觉效果不错，只是需要手动调整而已
